config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  resources :albums

  get '/welcome' => 'sessions#new', as: 'welcome'
  get '/auth/instagram', as: 'oauth'
  get '/auth/instagram/callback' =>'sessions#create'
  get '/signout' => 'sessions#destroy', as: 'signout'

end

app/models/album.rb
class Album < ActiveRecord::Base
  include Tokenable
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :owner, class_name: "User"
  has_many :photos, dependent: :destroy

  has_many :album_users, dependent: :destroy
  has_many :contributors, through: :album_users, source: :user

  validates :title, presence: true
  validates :public, inclusion: [true, false]

  def build_photos
    client = Instagram.client(access_token: self.owner.token)
    # Need to add pagination from result
    client.tag_recent_media(self.title, count: 33).each do |media|
      if allowed_nicknames.include?(media[:user][:username]) && media[:type] == "image"
        if Photo.where(:insta_id => media[:id], :album_id => self).empty?
        # create if it does not
          Photo.create! do |photo|
            photo.caption = media[:caption][:text]
            photo.media_url = media[:images][:standard_resolution][:url]
            photo.kind = media[:type]
            photo.insta_id = media[:id]
            if media[:location][:name]
              photo.latitude = media[:location][:latitude]
              photo.longitude = media[:location][:longitude]
              photo.location_name = media[:location][:name]
            end
            photo.posted_time = Time.at(media[:created_time].to_i).utc
            photo.album = self
            photo.user = User.find_by(:uid => media[:user][:id])
            # Need to fix order when photos are pulled in
            photo.order = Photo.where(album: self).count + 1
          end
        end
      end
    end
  end

  def build_contributors(usernames)
    client = Instagram.client(access_token: self.owner.token)
    usernames.collect do |username|
      if username != ""
        user = client.user_search(username).first
        if user
          contributor = User.find_or_create_contributor(user)
          self.contributors << contributor
          contributor
        end
      end
    end.compact
  end

  def remove_contributors(usernames)
    AlbumUser.joins(:user).where(:album_id => self, :users => {:nickname => usernames}).destroy_all
    Photo.joins(:user).where(:album_id => self, :users => {:nickname => usernames}).destroy_all
  end

  def allowed_nicknames
    (contributors + [owner]).collect(&:nickname).uniq
  end

  def self.build_with_owner(album_params, user)
    album = Album.new(album_params)
    album.owner = user
    album
  end

  def update_contributors(usernames)
    contributors = self.contributors.pluck(:nickname)
    added = []
    removed = contributors.dup
    usernames.each do |username|
      contributors.include?(username) ? removed.delete(username) : added << username
    end
    build_contributors(added)
    remove_contributors(removed)
  end

  def update_album(album_params)
    Photo.where(:album_id => self).destroy_all if self.title != album_params[:title]
    self.update(album_params)
  end

  def update_order(order_params)
    order_params[:tokens].split(',').each_with_index do |token, index|
      #TODO: refactor for less querying
      photo = Photo.find_by(:token => token)
      photo.order = index + 1
      photo.save
    end
  end
end

app/models/album_user.rb
class AlbumUser < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Tokenable
  belongs_to :album
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :albums, :foreign_key => 'owner_id'
  has_many :photos

  has_many :album_users
  has_many :contributions, through: :album_users, source: :album

  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_existing_user(auth_hash)|| User.create_with_omnihash(auth_hash)
  end

  def self.find_or_create_contributor(instagram_user)
    User.find_by(:uid => instagram_user[:id]) || User.create_with_instagram_user(instagram_user)
  end

  private
    def self.create_with_omnihash(auth_hash)
      User.create! do |user|
        user.nickname = auth_hash[:info][:nickname]
        user.name = auth_hash[:info][:name]
        user.image = auth_hash[:info][:image]
        user.provider = auth_hash[:provider]
        user.uid = auth_hash[:uid]
        user.token = auth_hash[:credentials][:token]
      end
    end

    def self.create_with_instagram_user(instagram_user)
        User.create! do |user|
          user.nickname = instagram_user[:username]
          user.name = instagram_user[:full_name]
          user.image = instagram_user[:profile_picture]
          user.provider = "instagram"
          user.uid = instagram_user[:id]
        end
    end

    def self.find_existing_user(auth_hash)
      User.where(:uid => auth_hash[:uid], :provider => auth_hash[:provider]).
        where.not(:token => nil).
        first
    end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :shared_album, only: [:show]

  def index
    @albums = current_user.albums
    @contributions = current_user.contributions
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.build_with_owner(album_params, current_user)
    @album.build_contributors(contributor_params[:names])
    @album.save ? (redirect_to @album) : (render 'new')
  end

  def show
    @album.build_photos if @album.owner == current_user
  end

  def edit
  end

  def update
    #TODO: refactor
    @album.update_order(order_params)
    @album.update_album(album_params)
    @album.update_contributors(contributor_params[:names])
    @album.save ? (redirect_to @album) : (render 'edit')
  end

  def destroy
    @album.destroy
    redirect_to root_path
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, :public)
    end

    def contributor_params
      params.require(:contributor).permit(:names => [])
    end

    def order_params
      params.require(:order).permit(:tokens)
    end

    def shared_album
      authenticate_user! if (params[:p] != @album.token) || !(@album.public)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user, :signed_in?

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def authenticate_user!
    if !signed_in?
      redirect_to welcome_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    login(@user)
    redirect_to root_path
  end

  def destroy
    logout
    redirect_to root_path
  end

  private
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper

  def ordered_photos(album)
    Photo.where(album_id: album).order(:order)
  end

  def show_edit_menu(album)
    if album.owner == current_user
      render 'albums/sidebar/edit', album: album
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_side_menu
    signed_in? ? (render 'layouts/sidemenu/signedin') : (render 'layouts/sidemenu/signedout')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/albums/_form.html.erb
<%= form_for album, :html => {id: "editForm"} do |f| %>
  <div class="form-group">
    <%= f.label :title, "Album Title", class: "control-label" %>
    <span>(The hashtag to be searched)</span>
    <%= f.text_field :title, class: "form-control input-sm" %>
  </div>

  <div class="form-group">
    <%= label_tag "Contributors" %>
    <span><a href="#" id="add_contributor">Add [+]</a>/<a href="#" id="remove_contributor">Remove [-]</a></span>
    <div id="contributors">
      <%- album.contributors.each do |contributor| -%>
        <%= text_field_tag "contributor[names][]", contributor.nickname, class: "input-sm contributor-input form-control" %>
      <%- end -%>
      <input type="text" name="contributor[names][]" class="input-sm contributor-input form-control">
    </div>
  </div>

  <div class="form-group">
    <%= label_tag "Private/Public Album" %>
    <div>
      <%= f.radio_button :public, 'true', :checked => true %>
      <%= label :public_true, 'Public', class: "radio-inline custom-radio" %>
      <%= f.radio_button :public, 'false' %>
      <%= label :public_false, 'Private', class: "radio-inline custom-radio" %>
    </div>
  </div>

  <%- if album.title != nil -%>
    <div class="form-group">
      <%= label_tag "Sort Photos" %>

      <div id="sortable">
        <%- ordered_photos(album).each do |photo| -%>

          <img class="ui-state-default sortable-photo" src="<%= photo.media_url %>">

        <%- end -%>
      </div>
      <input type="text" name="order[tokens]" id="orderSubmit">
    </div>
  <%- end -%>

  <div class="spacer-15"></div>
  <%= f.submit class: "btn btn-md btn-black" %>
  <%= link_to "Cancel", :back, class: "btn btn-md btn-black-line " %>
<%- end -%>

app/views/albums/_photo_sort.html.erb
<%= form_for album, :html => {id: "sortForm"} do |f| %>
  <ul id="sortable">
    <%- ordered_photos(album).each do |photo| -%>
    <li class="ui-state-default" id="<%= photo.token %>"><%= photo.location_name %> | Order: <%= photo.order %></li>
    <%- end -%>
  </ul>
  <input type="text" name="order[tokens]" id="orderSubmit">
  <%= f.submit "Update" %>
<%- end -%>

app/views/albums/_preview.html.erb
<div class="nf-item <%= type %> spacing">
  <div class="item-box">
    <%= link_to album do %>
      <img alt="1" src="<%= album.photos.sample.media_url %>" class="item-container">
      <div class="item-mask">
        <div class="item-caption">
          <h5 class="white"><%= album.title %></h5>
          <p class="white">@<%= album.owner.nickname %></p>
        </div>
      </div>
    <%- end -%>
  </div>
</div>

app/views/albums/edit.html.erb
<section class="ptb ptb-sm-80">
  <div class="container">
    <div class="col-md-offset-3 col-md-6 col-sm-12">
      <h3 class="legend">Update Album</h3>
        <div class="note">
          <p>NOTE: If the Title is updated, then all previous photos will be removed and new photos will be searched.</p>
          <p>If Contributors are removed, their photos will be deleted from the album.</p>
        </div>
        <%= render 'form', album: @album %>
    </div>
  </div>

  <!-- TODO: display photo and add ability to reorder photo (show small previews and drag/drop in order) -->
  <!-- <div class="container"> -->
    <%#= render 'albums/photo_sort', album: @album %>
</section>
<div class="clearfix"></div>

app/views/albums/index.html.erb
<section class="inner-intro bg-img14 overlay-light" style="background-size: cover !important; background-position: center center; background-image: url('<%= image_path("index.jpg") %>');">

  <div class="container">
    <div class="row title">
      <h2 class="h2">Albums</h2>
    </div>
  </div>
</section>
<div class="clearfix"></div>

<section class="ptb ptb-sm-80">
  <div class="container">
    <div class="row">
      <ul class="container-filter categories-filter">
        <li><a class="categories active" data-filter="*">All</a></li>
        <li><a class="categories" data-filter=".my_albums">My Albums</a></li>
        <li><a class="categories" data-filter=".tagged_albums">Other Albums</a></li>
        <li><%= link_to "New", new_album_path %></li>
      </ul>
    </div>
    <div class="row container-grid nf-col-3 display-container">
      <%= render partial: 'albums/preview', collection: @albums, as: :album, locals: {:type => "my_albums"} %>
      <%= render partial: 'albums/preview', collection: @contributions, as: :album, locals: {:type => "tagged_albums"}%>
    </div>
  </div>
</section>
<div class="clearfix"></div>

app/views/albums/new.html.erb
<section class="ptb ptb-sm-80">
  <div class="container">
    <div class="col-md-offset-3 col-md-6 col-sm-12">
      <h3 class="legend">New Album</h3>
      <%= render 'form', album: @album %>
    </div>
  </div>
</section>
<div class="clearfix"></div>

app/views/albums/show.html.erb
<section class="inner-intro bg-img14 overlay-light" style="background-size: cover !important; background-position: center center; background-image: url('<%= image_path("show.jpg") %>'); z-index: -1 !important;">
  <div class="container">
    <div class="row title">
      <h2 class="h2">#<%= @album.title %></h2>
    </div>
  </div>
</section>
<div class="clearfix"></div>

<section class="ptb ptb-sm-80">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 mt-xs-30">
        <%= render 'albums/sidebar/contributors', album: @album %>
        <%= show_edit_menu(@album) %>
      </div>

      <div class="col-md-9 col-sm-8">
        <div class="tabs b-lrb-none">
          <ul>
            <li><a href="#tabs-gallery" id="gallery"><i class="ion ion-images left"></i>Gallery</a></li>
            <li id="map-tab-button"><a href="#tabs-map" ><i class="ion ion-map left"></i>Map</a></li>
          </ul>
          <div class="ui-tab-content">
            <div id="tabs-gallery" class="plr-0">
              <%= render 'albums/show/gallery', album: @album %>
            </div>
            <div id="tabs-map" class="plr-0">
              <%= render 'albums/show/map', album: @album %>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</section>

app/views/albums/show/_gallery.html.erb
<div class="row">
  <ul class="container-filter categories-filter">
    <li><a class="categories active" data-filter="*">All</a></li>
    <li><a class="categories" data-filter=".<%= album.owner.nickname %>">@<%= album.owner.nickname %></a></li>
    <%- album.contributors.each do |contributor| -%>
    <li><a class="categories" data-filter=".<%= contributor.nickname %>">@<%= contributor.nickname %></a></li>
    <%- end -%>
  </ul>
</div>

<div class="row container-grid nf-col-3">
  <%= render partial: 'albums/show/images', collection: ordered_photos(album), as: :photo %>
</div>

app/views/albums/show/_globe.html.erb
<div id="earth_div" style="width:800px;height:600px;border:1px solid gray; padding:2px;"></div>

<%- chronological_photos(album).each do |photo| -%>
<!--   <%= image_tag photo.media_url %><br>
  <p><%= photo.caption %></p>
  <p>Photo taken at: <%= photo.location_name %> on <%= photo.posted_time %></p> -->
  <input type="button" value="Fly to <%= photo.location_name %>" data-coordinates="<%="[#{photo.latitude}, #{photo.longitude}]"  %>" data-location="<%= photo.location_name %>" data-src="<%= photo.media_url %>"  class="button"><br>
<%- end -%>

app/views/albums/show/_images.html.erb
<div class="nf-item <%= photo.user.nickname %> spacing">
  <div class="item-box">
  <a class="cbox-gallery1" href="<%= photo.media_url %>" title="<%= photo.location_name %>">
      <img alt="1" src="<%= photo.media_url %>" class="item-container" data-link="<%= photo.media_url %>" data-lat="<%= photo.latitude %>" data-long="<%= photo.longitude %>" data-name="<%= photo.location_name %>">
      <div class="item-mask">
        <div class="item-caption">
          <h5 class="white"><%= photo.location_name %></h5>
        </div>
      </div>
    </a>
  </div>
</div>

app/views/albums/show/_map.html.erb
<div class="icons">
  <span id="map-prev" class="map-nav"><i class="ion ion-chevron-left icon"></i></span>
  <span id="map-all" class="map-nav" ><i class="ion ion-flag icon"></i></span>
  <span id="map-next" class="map-nav"><i class="ion ion-chevron-right icon"></i></span>
</div>
<div id="leafmap"></div>

app/views/albums/sidebar/_contributors.html.erb
<div class="sidebar-widget">
  <h5>Contributors</h5>
  <hr>
  <ul>
      <li>@<%= album.owner.nickname %></li>
      <%- album.contributors.each do |contributor| -%>
      <li>@<%= contributor.nickname %></li>
      <%- end -%>
  </ul>
</div>

app/views/albums/sidebar/_edit.html.erb
<div class="sidebar-widget">
  <h5>Manage</h5>
  <hr>
  <ul>
    <%- if album.public -%>
    <li>
      <a data-toggle="modal" data-target="#shareModal">
        <i class="ion ion-share"></i> Share
      </a>
    </li>
    <%- end -%>
    <li>
      <%= link_to edit_album_path(album) do %>
        <i class="ion ion-edit"></i> Update
      <%- end -%>
    </li>
    <li>
      <%= link_to album, method: :delete do %>
        <i class="ion ion-trash-a"></i> Delete
      <%- end -%>
    </li>
  </ul>
</div>



<!-- Modal -->
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog share">
    <h2 class="not-visible" id='feedback'> Copied!</h2>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Public URL</h4>
      </div>
      <div class="modal-body">
        <p id="public-url"><%= "#{request.protocol}#{request.host_with_port}/albums/#{album.slug}?p=#{album.token}" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="copy" type="copy">Copy</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer pt-80">
  <div class="container">
    <div class="row mb-60">
      <div class="col-md-4 col-md-offset-4 col-xs-12">
        <div class="create-header">
          <center>Created By</center>
        </div>
        <div class="creator center">
          <p id="creator-name">Seiji Naganuma</p>
          <ul class="social">
              <li><a target="_blank" href="https://github.com/snags88"><i class="fa fa-github"></i></a></li>
              <li><a target="_blank" href="https://www.linkedin.com/in/snaganuma"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <div class="logo">
      <%= link_to root_path do %>
        <h3>[glance]</h3>
      <%- end -%>
    </div>

    <div class="side-menu-btn" id="menu-button">
        <ul>
          <li class="">
            <a class="right-icon bar-icon toggle-menu menu-right push-body"><i class="fa fa-bars"></i></a>
          </li>
        </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>glance</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
  <body class="full-intro">

    <%= render "layouts/sidemenu/menu" %>

    <div class="wrapper">
      <%= render "layouts/header" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/sidemenu/_menu.html.erb
<section class="side-menu cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right">
  <a class="menu-close toggle-menu menu-right push-body"><i class="ion ion-android-close"></i></a>
  <%= show_side_menu %>
</section>

app/views/layouts/sidemenu/_signedin.html.erb
<div class="sign-in">
  <div id="profile-image-container">
    <%= image_tag current_user.image, :class => "profile-image" %>
  </div>
  <h5 class="white greeting">@<%= current_user.nickname %></h5>
</div>
<ul>
    <li><%= link_to "My Albums", root_path %></li>
    <li><%= link_to "New Album", new_album_path %></li>
    <li class="boundry"></li>
    <li><%= link_to "Sign out", signout_path %></li>
</ul>

app/views/layouts/sidemenu/_signedout.html.erb
<div class="sign-in">
  <h5 class="white">Sign In</h5>
  <i class="fa fa-instagram"></i> <%= link_to "Sign in w/ Instagram", oauth_path %>
</div>
<ul>

</ul>